export enum MicroservicesStorageEvents {
  MEDIA_STARTED = 'event.MEDIA_STARTED',
  MEDIA_PROGRESS = 'event.MEDIA_PROGRESS',
  MEDIA_COMPLETED = 'event.MEDIA_COMPLETED',
  
  MEDIA_FETCHED_BY_ID = 'event.MEDIA_FETCHED_BY_ID',
  MEDIA_FETCHED_ALL = 'event.MEDIA_FETCHED_ALL',
}