export const MicroservicesErrorEventName: string = `MICROSERVICE-ERROR`;

export enum MicroservicesStorageEvents {
  MEDIA_STARTED = 'event.MEDIA_STARTED',
  MEDIA_PROGRESSED = 'event.MEDIA_PROGRESSED',
  MEDIA_AGGREGATING = 'MEDIA_AGGREGATING',
  MEDIA_COMPLETED = 'MEDIA_COMPLETED',
  MEDIA_FETCHED_BY_ID = 'event.MEDIA_FETCHED_BY_ID',
  MEDIA_FETCHED_ALL = 'event.MEDIA_FETCHED_ALL',
}

export enum MicroservicesUsersEvents {
  USER_FETCHED_BY_ID = 'request.USER_FETCHED_BY_ID',
  USER_FETCHED_BY_EMAIL = 'request.USER_FETCHED_BY_EMAIL',
  USER_FETCHED_BY_USERNAME = 'request.USER_FETCHED_BY_USERNAME',
  USERS_FETCHED_LIKE_USERNAME = 'request.USERS_FETCHED_LIKE_USERNAME',
  USER_AUTHENTICATED = "request.USER_AUTHENTICATED",
  USER_CREATED = "request.USER_CREATED",
  USER_UPDATED = "request.USER_UPDATED",
  USER_DELETED = "request.USER_DELETED",
}

export enum MicroservicesBlogEvents {
  POST_FETCHED_BY_ID = 'request.POST_FETCHED_BY_ID',
  POSTS_FETCHED_BY_USERID = 'request.POSTS_FETCHED_BY_USERID',
  POSTS_FETCHED_BY_TAG = 'request.POSTS_FETCHED_BY_TAG',
  POST_CREATED = "request.POST_CREATED",
  POST_UPDATED = "request.POST_UPDATED",
  POST_DELETED = "request.POST_DELETED",
  POST_LIKED = "request.POST_LIKED",
  POST_SAVED = "request.POST_SAVED",

  COMMENT_FETCHED_BY_ID = 'request.COMMENT_FETCHED_BY_ID',
  COMMENTS_FETCHED_BY_USERID = 'request.COMMENTS_FETCHED_BY_USERID',
  COMMENTS_FETCHED_BY_TAG = 'request.COMMENTS_FETCHED_BY_TAG',
  COMMENT_CREATED = "request.COMMENT_CREATED",
  COMMENT_UPDATED = "request.COMMENT_UPDATED",
  COMMENT_DELETED = "request.COMMENT_DELETED",
  COMMENT_LIKED = "request.COMMENT_LIKED",
  COMMENT_SAVED = "request.COMMENT_SAVED",

  REPLY_FETCHED_BY_ID = 'request.REPLY_FETCHED_BY_ID',
  REPLIES_FETCHED_BY_USERID = 'request.REPLIES_FETCHED_BY_USERID',
  REPLIES_FETCHED_BY_TAG = 'request.REPLIES_FETCHED_BY_TAG',
  REPLY_CREATED = "request.REPLY_CREATED",
  REPLY_UPDATED = "request.REPLY_UPDATED",
  REPLY_DELETED = "request.REPLY_DELETED",
  REPLY_LIKED = "request.REPLY_LIKED",
  REPLY_SAVED = "request.REPLY_SAVED",
}

