export const counties = [
  "Suffolk",
  "Adjuntas",
  "Aguada",
  "Aguadilla",
  "Maricao",
  "Anasco",
  "Utuado",
  "Arecibo",
  "Barceloneta",
  "Cabo Rojo",
  "Penuelas",
  "Camuy",
  "Lares",
  "San German",
  "Sabana Grande",
  "Ciales",
  "Dorado",
  "Guanica",
  "Florida",
  "Guayanilla",
  "Hatillo",
  "Hormigueros",
  "Isabela",
  "Jayuya",
  "Lajas",
  "Las Marias",
  "Manati",
  "Moca",
  "Rincon",
  "Quebradillas",
  "Mayaguez",
  "San Sebastian",
  "Morovis",
  "Vega Alta",
  "Vega Baja",
  "Yauco",
  "Aguas Buenas",
  "Guayama",
  "Aibonito",
  "Maunabo",
  "Arroyo",
  "Ponce",
  "Naguabo",
  "Naranjito",
  "Orocovis",
  "Rio Grande",
  "Patillas",
  "Caguas",
  "Canovanas",
  "Ceiba",
  "Cayey",
  "Fajardo",
  "Cidra",
  "Humacao",
  "Salinas",
  "San Lorenzo",
  "Santa Isabel",
  "Vieques",
  "Villalba",
  "Yabucoa",
  "Coamo",
  "Las Piedras",
  "Loiza",
  "Luquillo",
  "Culebra",
  "Juncos",
  "Gurabo",
  "Comerio",
  "Corozal",
  "Barranquitas",
  "Juana Diaz",
  "Saint Thomas",
  "Saint Croix",
  "Saint John",
  "San Juan",
  "Bayamon",
  "Toa Baja",
  "Toa Alta",
  "Catano",
  "Guaynabo",
  "Trujillo Alto",
  "Carolina",
  "Hampden",
  "Hampshire",
  "Worcester",
  "Berkshire",
  "Franklin",
  "Middlesex",
  "Essex",
  "Plymouth",
  "Norfolk",
  "Bristol",
  "Barnstable",
  "Dukes",
  "Nantucket",
  "Newport",
  "Providence",
  "Washington",
  "Kent",
  "Hillsborough",
  "Rockingham",
  "Merrimack",
  "Grafton",
  "Belknap",
  "Carroll",
  "Sullivan",
  "Cheshire",
  "Coos",
  "Strafford",
  "York",
  "Cumberland",
  "Sagadahoc",
  "Oxford",
  "Androscoggin",
  "Kennebec",
  "Lincoln",
  "Waldo",
  "Penobscot",
  "Piscataquis",
  "Hancock",
  "Aroostook",
  "Somerset",
  "Knox",
  "Windsor",
  "Orange",
  "Caledonia",
  "Windham",
  "Bennington",
  "Chittenden",
  "Grand Isle",
  "Lamoille",
  "Addison",
  "Rutland",
  "Orleans",
  "Hartford",
  "Litchfield",
  "Tolland",
  "New London",
  "New Haven",
  "Fairfield",
  "Hudson",
  "Morris",
  "Bergen",
  "Passaic",
  "Union",
  "Sussex",
  "Monmouth",
  "Warren",
  "Hunterdon",
  "Salem",
  "Camden",
  "Ocean",
  "Burlington",
  "Gloucester",
  "Atlantic",
  "Cape May",
  "Mercer",
  "",
  "New York",
  "Richmond",
  "Bronx",
  "Westchester",
  "Putnam",
  "Rockland",
  "Nassau",
  "Queens",
  "Kings",
  "Albany",
  "Schenectady",
  "Montgomery",
  "Greene",
  "Columbia",
  "Rensselaer",
  "Saratoga",
  "Fulton",
  "Schoharie",
  "Otsego",
  "Hamilton",
  "Delaware",
  "Ulster",
  "Dutchess",
  "Clinton",
  "Saint Lawrence",
  "Onondaga",
  "Cayuga",
  "Oswego",
  "Madison",
  "Cortland",
  "Tompkins",
  "Oneida",
  "Seneca",
  "Chenango",
  "Wayne",
  "Lewis",
  "Herkimer",
  "Jefferson",
  "Tioga",
  "Broome",
  "Erie",
  "Genesee",
  "Niagara",
  "Wyoming",
  "Allegany",
  "Cattaraugus",
  "Chautauqua",
  "Monroe",
  "Livingston",
  "Yates",
  "Ontario",
  "Steuben",
  "Schuyler",
  "Chemung",
  "Beaver",
  "Allegheny",
  "Fayette",
  "Westmoreland",
  "Bedford",
  "Armstrong",
  "Indiana",
  "Cambria",
  "Clearfield",
  "Elk",
  "Forest",
  "Cameron",
  "Butler",
  "Clarion",
  "Lawrence",
  "Crawford",
  "Venango",
  "Mckean",
  "Blair",
  "Huntingdon",
  "Centre",
  "Potter",
  "Bradford",
  "Mifflin",
  "Lebanon",
  "Dauphin",
  "Perry",
  "Juniata",
  "Northumberland",
  "Lancaster",
  "Adams",
  "Lycoming",
  "Snyder",
  "Montour",
  "Schuylkill",
  "Northampton",
  "Lehigh",
  "Carbon",
  "Bucks",
  "Berks",
  "Luzerne",
  "Pike",
  "Lackawanna",
  "Susquehanna",
  "Philadelphia",
  "Chester",
  "New Castle",
  "District Of Columbia",
  "Loudoun",
  "Rappahannock",
  "Manassas City",
  "Manassas Park City",
  "Fauquier",
  "Fairfax",
  "Prince William",
  "Charles",
  "Saint Marys",
  "Prince Georges",
  "Calvert",
  "Howard",
  "Anne Arundel",
  "Harford",
  "Baltimore",
  "Baltimore City",
  "Garrett",
  "Talbot",
  "Queen Annes",
  "Caroline",
  "Dorchester",
  "Frederick",
  "Wicomico",
  "Cecil",
  "Fairfax City",
  "Falls Church City",
  "Arlington",
  "Alexandria City",
  "Fredericksburg City",
  "Stafford",
  "Spotsylvania",
  "King George",
  "Winchester City",
  "Clarke",
  "Shenandoah",
  "Page",
  "Culpeper",
  "Harrisonburg City",
  "Augusta",
  "Albemarle",
  "Charlottesville City",
  "Nelson",
  "Fluvanna",
  "Waynesboro City",
  "Amelia",
  "Buckingham",
  "Hanover",
  "King William",
  "New Kent",
  "Goochland",
  "Mathews",
  "King And Queen",
  "Louisa",
  "Charles City",
  "Henrico",
  "James City",
  "Powhatan",
  "Chesterfield",
  "Richmond City",
  "Williamsburg City",
  "Accomack",
  "Isle Of Wight",
  "Chesapeake City",
  "Suffolk City",
  "Virginia Beach City",
  "Norfolk City",
  "Newport News City",
  "Hampton City",
  "Poquoson City",
  "Portsmouth City",
  "Prince George",
  "Petersburg City",
  "Brunswick",
  "Dinwiddie",
  "Nottoway",
  "Southampton",
  "Colonial Heights City",
  "Surry",
  "Emporia City",
  "Franklin City",
  "Hopewell City",
  "Greensville",
  "Prince Edward",
  "Mecklenburg",
  "Charlotte",
  "Lunenburg",
  "Appomattox",
  "Roanoke City",
  "Roanoke",
  "Botetourt",
  "Patrick",
  "Henry",
  "Pulaski",
  "Pittsylvania",
  "Floyd",
  "Giles",
  "Martinsville City",
  "Craig",
  "Radford",
  "Wise",
  "Dickenson",
  "Lee",
  "Russell",
  "Buchanan",
  "Scott",
  "Norton City",
  "Grayson",
  "Smyth",
  "Wythe",
  "Bland",
  "Galax City",
  "Tazewell",
  "Staunton City",
  "Bath",
  "Highland",
  "Rockbridge",
  "Buena Vista City",
  "Clifton Forge City",
  "Covington City",
  "Alleghany",
  "Lexington City",
  "Lynchburg City",
  "Campbell",
  "Halifax",
  "Amherst",
  "Bedford City",
  "Danville City",
  "Mcdowell",
  "Mingo",
  "Greenbrier",
  "Pocahontas",
  "Summers",
  "Kanawha",
  "Raleigh",
  "Roane",
  "Boone",
  "Clay",
  "Logan",
  "Nicholas",
  "Mason",
  "Jackson",
  "Calhoun",
  "Gilmer",
  "Berkeley",
  "Morgan",
  "Cabell",
  "Ohio",
  "Brooke",
  "Marshall",
  "Wood",
  "Pleasants",
  "Tyler",
  "Wirt",
  "Ritchie",
  "Wetzel",
  "Upshur",
  "Webster",
  "Randolph",
  "Barbour",
  "Tucker",
  "Harrison",
  "Doddridge",
  "Braxton",
  "Taylor",
  "Preston",
  "Monongalia",
  "Marion",
  "Grant",
  "Mineral",
  "Hardy",
  "Pendleton",
  "Davie",
  "Forsyth",
  "Yadkin",
  "Rowan",
  "Stokes",
  "Alamance",
  "Chatham",
  "Caswell",
  "Guilford",
  "Davidson",
  "Moore",
  "Person",
  "Harnett",
  "Wake",
  "Durham",
  "Johnston",
  "Granville",
  "Vance",
  "Edgecombe",
  "Nash",
  "Bertie",
  "Beaufort",
  "Pitt",
  "Wilson",
  "Hertford",
  "Hyde",
  "Martin",
  "Pasquotank",
  "Dare",
  "Currituck",
  "Perquimans",
  "Tyrrell",
  "Gates",
  "Chowan",
  "Stanly",
  "Gaston",
  "Anson",
  "Iredell",
  "Cleveland",
  "Rutherford",
  "Cabarrus",
  "Sampson",
  "Robeson",
  "Bladen",
  "Duplin",
  "Scotland",
  "Hoke",
  "New Hanover",
  "Pender",
  "Columbus",
  "Onslow",
  "Lenoir",
  "Pamlico",
  "Carteret",
  "Craven",
  "Jones",
  "Catawba",
  "Avery",
  "Watauga",
  "Wilkes",
  "Caldwell",
  "Burke",
  "Ashe",
  "Alexander",
  "Buncombe",
  "Swain",
  "Mitchell",
  "Transylvania",
  "Henderson",
  "Yancey",
  "Haywood",
  "Polk",
  "Graham",
  "Macon",
  "Cherokee",
  "Clarendon",
  "Richland",
  "Bamberg",
  "Lexington",
  "Kershaw",
  "Orangeburg",
  "Newberry",
  "Sumter",
  "Williamsburg",
  "Darlington",
  "Colleton",
  "Saluda",
  "Florence",
  "Aiken",
  "Spartanburg",
  "Laurens",
  "Charleston",
  "Georgetown",
  "Horry",
  "Marlboro",
  "Dillon",
  "Greenville",
  "Abbeville",
  "Anderson",
  "Pickens",
  "Oconee",
  "Greenwood",
  "Allendale",
  "Barnwell",
  "Mccormick",
  "Edgefield",
  "Hampton",
  "Jasper",
  "Dekalb",
  "Gwinnett",
  "Cobb",
  "Barrow",
  "Rockdale",
  "Newton",
  "Walton",
  "Bartow",
  "Haralson",
  "Douglas",
  "Paulding",
  "Gordon",
  "Lamar",
  "Spalding",
  "Butts",
  "Heard",
  "Meriwether",
  "Coweta",
  "Troup",
  "Clayton",
  "Upson",
  "Emanuel",
  "Wheeler",
  "Evans",
  "Bulloch",
  "Tattnall",
  "Screven",
  "Toombs",
  "Candler",
  "Jenkins",
  "Treutlen",
  "Hall",
  "Habersham",
  "Banks",
  "Fannin",
  "Hart",
  "Rabun",
  "White",
  "Lumpkin",
  "Dawson",
  "Stephens",
  "Towns",
  "Oglethorpe",
  "Elbert",
  "Taliaferro",
  "Murray",
  "Walker",
  "Whitfield",
  "Catoosa",
  "Chattooga",
  "Dade",
  "Mcduffie",
  "Glascock",
  "Wilcox",
  "Wilkinson",
  "Houston",
  "Dooly",
  "Peach",
  "Crisp",
  "Dodge",
  "Bleckley",
  "Twiggs",
  "Baldwin",
  "Telfair",
  "Johnson",
  "Bibb",
  "Liberty",
  "Effingham",
  "Mcintosh",
  "Bryan",
  "Long",
  "Ware",
  "Bacon",
  "Coffee",
  "Appling",
  "Pierce",
  "Glynn",
  "Jeff Davis",
  "Charlton",
  "Brantley",
  "Lowndes",
  "Cook",
  "Berrien",
  "Clinch",
  "Atkinson",
  "Brooks",
  "Thomas",
  "Lanier",
  "Echols",
  "Dougherty",
  "Turner",
  "Decatur",
  "Colquitt",
  "Early",
  "Terrell",
  "Tift",
  "Grady",
  "Miller",
  "Seminole",
  "Ben Hill",
  "Quitman",
  "Irwin",
  "Baker",
  "Worth",
  "Harris",
  "Chattahoochee",
  "Schley",
  "Muscogee",
  "Stewart",
  "Saint Johns",
  "Suwannee",
  "Lafayette",
  "Duval",
  "Lake",
  "Volusia",
  "Flagler",
  "Leon",
  "Wakulla",
  "Gadsden",
  "Bay",
  "Holmes",
  "Gulf",
  "Escambia",
  "Santa Rosa",
  "Okaloosa",
  "Alachua",
  "Gilchrist",
  "Levy",
  "Dixie",
  "Brevard",
  "Indian River",
  "Miami-Dade",
  "Broward",
  "Palm Beach",
  "Hendry",
  "Glades",
  "Pasco",
  "Pinellas",
  "Highlands",
  "Hardee",
  "Osceola",
  "Collier",
  "Manatee",
  "Sarasota",
  "De Soto",
  "Citrus",
  "Hernando",
  "Saint Lucie",
  "Okeechobee",
  "Saint Clair",
  "Shelby",
  "Tallapoosa",
  "Blount",
  "Talladega",
  "Cullman",
  "Chilton",
  "Coosa",
  "Tuscaloosa",
  "Hale",
  "Winston",
  "Lauderdale",
  "Limestone",
  "Colbert",
  "Etowah",
  "De Kalb",
  "Autauga",
  "Crenshaw",
  "Elmore",
  "Bullock",
  "Covington",
  "Cleburne",
  "Dale",
  "Geneva",
  "Conecuh",
  "Mobile",
  "Dallas",
  "Marengo",
  "Chambers",
  "Choctaw",
  "Robertson",
  "Williamson",
  "Cheatham",
  "Cannon",
  "Sumner",
  "Hickman",
  "Dickson",
  "Smith",
  "Trousdale",
  "Humphreys",
  "Maury",
  "Grundy",
  "Mcminn",
  "Bradley",
  "Rhea",
  "Meigs",
  "Sequatchie",
  "Bledsoe",
  "Hawkins",
  "Carter",
  "Unicoi",
  "Claiborne",
  "Grainger",
  "Cocke",
  "Sevier",
  "Loudon",
  "Hamblen",
  "Crockett",
  "Tipton",
  "Dyer",
  "Hardeman",
  "Benton",
  "Weakley",
  "Obion",
  "Gibson",
  "Mcnairy",
  "Hardin",
  "Fentress",
  "Overton",
  "Pickett",
  "Van Buren",
  "Tate",
  "Panola",
  "Tippah",
  "Coahoma",
  "Tunica",
  "Bolivar",
  "Sharkey",
  "Sunflower",
  "Issaquena",
  "Pontotoc",
  "Tishomingo",
  "Prentiss",
  "Alcorn",
  "Itawamba",
  "Chickasaw",
  "Grenada",
  "Tallahatchie",
  "Yalobusha",
  "Leflore",
  "Yazoo",
  "Hinds",
  "Rankin",
  "Simpson",
  "Leake",
  "Copiah",
  "Attala",
  "Kemper",
  "Noxubee",
  "Neshoba",
  "Forrest",
  "Jefferson Davis",
  "Pearl River",
  "George",
  "Stone",
  "Amite",
  "Walthall",
  "Oktibbeha",
  "Trimble",
  "Oldham",
  "Spencer",
  "Bullitt",
  "Meade",
  "Breckinridge",
  "Powell",
  "Menifee",
  "Clark",
  "Estill",
  "Jessamine",
  "Woodford",
  "Bourbon",
  "Owen",
  "Rockcastle",
  "Garrard",
  "Boyle",
  "Whitley",
  "Laurel",
  "Harlan",
  "Leslie",
  "Bell",
  "Letcher",
  "Bracken",
  "Kenton",
  "Fleming",
  "Gallatin",
  "Boyd",
  "Greenup",
  "Elliott",
  "Wolfe",
  "Breathitt",
  "Owsley",
  "Magoffin",
  "Knott",
  "Mccracken",
  "Calloway",
  "Carlisle",
  "Ballard",
  "Graves",
  "Crittenden",
  "Lyon",
  "Allen",
  "Barren",
  "Metcalfe",
  "Edmonson",
  "Todd",
  "Trigg",
  "Christian",
  "Daviess",
  "Muhlenberg",
  "Mclean",
  "Hopkins",
  "Casey",
  "Mccreary",
  "Adair",
  "Larue",
  "Green",
  "Licking",
  "Champaign",
  "Ross",
  "Pickaway",
  "Hocking",
  "Morrow",
  "Wyandot",
  "Sandusky",
  "Ottawa",
  "Lucas",
  "Williams",
  "Defiance",
  "Muskingum",
  "Noble",
  "Belmont",
  "Guernsey",
  "Coshocton",
  "Tuscarawas",
  "Columbiana",
  "Lorain",
  "Ashtabula",
  "Cuyahoga",
  "Geauga",
  "Summit",
  "Portage",
  "Medina",
  "Mahoning",
  "Trumbull",
  "Stark",
  "Ashland",
  "Huron",
  "Preble",
  "Brown",
  "Clermont",
  "Darke",
  "Miami",
  "Gallia",
  "Vinton",
  "Scioto",
  "Athens",
  "Auglaize",
  "Van Wert",
  "Hendricks",
  "Rush",
  "Porter",
  "La Porte",
  "Starke",
  "Kosciusko",
  "Elkhart",
  "St Joseph",
  "Lagrange",
  "Huntington",
  "Wells",
  "Cass",
  "Wabash",
  "Dearborn",
  "Ripley",
  "Switzerland",
  "Bartholomew",
  "Jennings",
  "Jay",
  "Blackford",
  "Dubois",
  "Warrick",
  "Posey",
  "Vanderburgh",
  "Vigo",
  "Parke",
  "Vermillion",
  "Tippecanoe",
  "Fountain",
  "Lapeer",
  "Macomb",
  "Oakland",
  "Washtenaw",
  "Sanilac",
  "Shiawassee",
  "Saginaw",
  "Tuscola",
  "Ogemaw",
  "Gladwin",
  "Gratiot",
  "Clare",
  "Midland",
  "Oscoda",
  "Roscommon",
  "Arenac",
  "Alcona",
  "Iosco",
  "Isabella",
  "Ingham",
  "Ionia",
  "Montcalm",
  "Eaton",
  "Barry",
  "Kalamazoo",
  "Allegan",
  "Branch",
  "Saint Joseph",
  "Lenawee",
  "Hillsdale",
  "Muskegon",
  "Mecosta",
  "Newaygo",
  "Oceana",
  "Wexford",
  "Grand Traverse",
  "Antrim",
  "Manistee",
  "Benzie",
  "Leelanau",
  "Missaukee",
  "Kalkaska",
  "Cheboygan",
  "Emmet",
  "Alpena",
  "Montmorency",
  "Chippewa",
  "Charlevoix",
  "Mackinac",
  "Presque Isle",
  "Dickinson",
  "Keweenaw",
  "Alger",
  "Delta",
  "Marquette",
  "Menominee",
  "Schoolcraft",
  "Luce",
  "Iron",
  "Houghton",
  "Baraga",
  "Ontonagon",
  "Gogebic",
  "Story",
  "Audubon",
  "Guthrie",
  "Mahaska",
  "Wright",
  "Ringgold",
  "Keokuk",
  "Poweshiek",
  "Tama",
  "Cerro Gordo",
  "Winnebago",
  "Kossuth",
  "Buena Vista",
  "Palo Alto",
  "Humboldt",
  "Sac",
  "Black Hawk",
  "Bremer",
  "Sioux",
  "Woodbury",
  "Ida",
  "Obrien",
  "Monona",
  "Pottawattamie",
  "Mills",
  "Fremont",
  "Dubuque",
  "Winneshiek",
  "Allamakee",
  "Linn",
  "Iowa",
  "Cedar",
  "Wapello",
  "Davis",
  "Appanoose",
  "Des Moines",
  "Muscatine",
  "Sheboygan",
  "Ozaukee",
  "Waukesha",
  "Fond Du Lac",
  "Calumet",
  "Manitowoc",
  "Kenosha",
  "Racine",
  "Milwaukee",
  "Walworth",
  "Rock",
  "Dane",
  "Sauk",
  "Green Lake",
  "Juneau",
  "Oconto",
  "Marinette",
  "Outagamie",
  "Shawano",
  "Kewaunee",
  "Door",
  "Marathon",
  "Langlade",
  "Price",
  "Vilas",
  "Rusk",
  "La Crosse",
  "Buffalo",
  "Trempealeau",
  "Vernon",
  "Eau Claire",
  "Pepin",
  "Dunn",
  "Barron",
  "Washburn",
  "Bayfield",
  "Sawyer",
  "Burnett",
  "Waupaca",
  "Waushara",
  "Chisago",
  "Anoka",
  "Isanti",
  "Pine",
  "Goodhue",
  "Dakota",
  "Rice",
  "Wabasha",
  "Steele",
  "Kanabec",
  "Ramsey",
  "Hennepin",
  "Sibley",
  "Sherburne",
  "Renville",
  "Mcleod",
  "Carver",
  "Meeker",
  "Stearns",
  "Mille Lacs",
  "Saint Louis",
  "Carlton",
  "Itasca",
  "Aitkin",
  "Olmsted",
  "Mower",
  "Winona",
  "Fillmore",
  "Blue Earth",
  "Nicollet",
  "Freeborn",
  "Faribault",
  "Le Sueur",
  "Watonwan",
  "Waseca",
  "Redwood",
  "Cottonwood",
  "Nobles",
  "Pipestone",
  "Kandiyohi",
  "Stevens",
  "Swift",
  "Big Stone",
  "Lac Qui Parle",
  "Traverse",
  "Yellow Medicine",
  "Morrison",
  "Pope",
  "Otter Tail",
  "Crow Wing",
  "Hubbard",
  "Wadena",
  "Becker",
  "Norman",
  "Mahnomen",
  "Wilkin",
  "Beltrami",
  "Clearwater",
  "Lake Of The Woods",
  "Koochiching",
  "Roseau",
  "Pennington",
  "Red Lake",
  "Kittson",
  "Brookings",
  "Minnehaha",
  "Mccook",
  "Moody",
  "Hutchinson",
  "Yankton",
  "Kingsbury",
  "Bon Homme",
  "Codington",
  "Deuel",
  "Day",
  "Hamlin",
  "Roberts",
  "Davison",
  "Hanson",
  "Jerauld",
  "Sanborn",
  "Gregory",
  "Miner",
  "Beadle",
  "Brule",
  "Charles Mix",
  "Hand",
  "Lyman",
  "Aurora",
  "Spink",
  "Edmunds",
  "Faulk",
  "Mcpherson",
  "Hughes",
  "Sully",
  "Tripp",
  "Stanley",
  "Bennett",
  "Haakon",
  "Mellette",
  "Perkins",
  "Corson",
  "Ziebach",
  "Dewey",
  "Harding",
  "Shannon",
  "Butte",
  "Custer",
  "Fall River",
  "Traill",
  "Sargent",
  "Ransom",
  "Barnes",
  "Grand Forks",
  "Walsh",
  "Pembina",
  "Cavalier",
  "Rolette",
  "Towner",
  "Bottineau",
  "Benson",
  "Eddy",
  "Stutsman",
  "Lamoure",
  "Griggs",
  "Foster",
  "Kidder",
  "Sheridan",
  "Dickey",
  "Burleigh",
  "Morton",
  "Emmons",
  "Oliver",
  "Slope",
  "Golden Valley",
  "Bowman",
  "Billings",
  "Mckenzie",
  "Hettinger",
  "Ward",
  "Mchenry",
  "Divide",
  "Mountrail",
  "Stillwater",
  "Yellowstone",
  "Rosebud",
  "Treasure",
  "Sweet Grass",
  "Big Horn",
  "Park",
  "Fergus",
  "Wheatland",
  "Meagher",
  "Musselshell",
  "Garfield",
  "Powder River",
  "Petroleum",
  "Roosevelt",
  "Mccone",
  "Daniels",
  "Valley",
  "Phillips",
  "Fallon",
  "Prairie",
  "Wibaux",
  "Cascade",
  "Lewis And Clark",
  "Glacier",
  "Pondera",
  "Teton",
  "Chouteau",
  "Toole",
  "Judith Basin",
  "Hill",
  "Blaine",
  "Broadwater",
  "Silver Bow",
  "Deer Lodge",
  "Beaverhead",
  "Missoula",
  "Ravalli",
  "Sanders",
  "Granite",
  "Flathead",
  "Du Page",
  "Kane",
  "Ogle",
  "Will",
  "La Salle",
  "Kendall",
  "Kankakee",
  "Iroquois",
  "Ford",
  "Vermilion",
  "Jo Daviess",
  "Stephenson",
  "Whiteside",
  "Rock Island",
  "Bureau",
  "Mcdonough",
  "Peoria",
  "Dewitt",
  "Piatt",
  "Coles",
  "Moultrie",
  "Edgar",
  "Macoupin",
  "Jersey",
  "Bond",
  "Edwards",
  "Sangamon",
  "Menard",
  "Massac",
  "Saline",
  "Saint Francois",
  "Gasconade",
  "Saint Louis City",
  "Saint Charles",
  "Audrain",
  "Callaway",
  "Ralls",
  "Reynolds",
  "Sainte Genevieve",
  "Bollinger",
  "Cape Girardeau",
  "Stoddard",
  "Mississippi",
  "Dunklin",
  "Pemiscot",
  "New Madrid",
  "Ray",
  "Platte",
  "Gentry",
  "Andrew",
  "Nodaway",
  "Holt",
  "Atchison",
  "Chariton",
  "Bates",
  "Barton",
  "Mcdonald",
  "Osage",
  "Maries",
  "Moniteau",
  "Cole",
  "Cooper",
  "Pettis",
  "Phelps",
  "Texas",
  "Dent",
  "Laclede",
  "Howell",
  "Oregon",
  "Ozark",
  "Taney",
  "Hickory",
  "Leavenworth",
  "Doniphan",
  "Wyandotte",
  "Wabaunsee",
  "Shawnee",
  "Nemaha",
  "Pottawatomie",
  "Geary",
  "Riley",
  "Neosho",
  "Woodson",
  "Coffey",
  "Chase",
  "Cloud",
  "Republic",
  "Jewell",
  "Sedgwick",
  "Harper",
  "Cowley",
  "Harvey",
  "Pratt",
  "Comanche",
  "Kingman",
  "Kiowa",
  "Barber",
  "Labette",
  "Osborne",
  "Ellsworth",
  "Reno",
  "Ness",
  "Pawnee",
  "Ellis",
  "Norton",
  "Trego",
  "Rooks",
  "Rawlins",
  "Cheyenne",
  "Sherman",
  "Gove",
  "Wallace",
  "Gray",
  "Kearny",
  "Lane",
  "Finney",
  "Hodgeman",
  "Stanton",
  "Seward",
  "Wichita",
  "Haskell",
  "Greeley",
  "Saunders",
  "Cuming",
  "Sarpy",
  "Burt",
  "Thurston",
  "Gage",
  "Thayer",
  "Otoe",
  "Richardson",
  "Nance",
  "Merrick",
  "Colfax",
  "Antelope",
  "Dixon",
  "Keya Paha",
  "Loup",
  "Furnas",
  "Kearney",
  "Gosper",
  "Nuckolls",
  "Red Willow",
  "Dundy",
  "Hitchcock",
  "Frontier",
  "Hayes",
  "Arthur",
  "Morrill",
  "Keith",
  "Kimball",
  "Cherry",
  "Garden",
  "Hooker",
  "Box Butte",
  "Dawes",
  "Scotts Bluff",
  "Banner",
  "Saint Bernard",
  "Plaquemines",
  "St John The Baptist",
  "Saint James",
  "Lafourche",
  "Assumption",
  "Saint Mary",
  "Terrebonne",
  "Ascension",
  "Tangipahoa",
  "Saint Tammany",
  "Saint Helena",
  "Saint Landry",
  "Iberia",
  "Evangeline",
  "Acadia",
  "Saint Martin",
  "Calcasieu",
  "Beauregard",
  "East Baton Rouge",
  "West Baton Rouge",
  "West Feliciana",
  "Pointe Coupee",
  "Iberville",
  "East Feliciana",
  "Bienville",
  "Natchitoches",
  "Caddo",
  "Bossier",
  "Red River",
  "Sabine",
  "Ouachita",
  "Morehouse",
  "West Carroll",
  "East Carroll",
  "Rapides",
  "Concordia",
  "Avoyelles",
  "Catahoula",
  "Tensas",
  "Winn",
  "Desha",
  "Ashley",
  "Chicot",
  "Drew",
  "Nevada",
  "Hempstead",
  "Little River",
  "Garland",
  "Hot Spring",
  "Arkansas",
  "Woodruff",
  "Lonoke",
  "Conway",
  "Faulkner",
  "Independence",
  "Cross",
  "Saint Francis",
  "Poinsett",
  "Craighead",
  "Sharp",
  "Izard",
  "Baxter",
  "Searcy",
  "Yell",
  "Sebastian",
  "Oklahoma",
  "Mcclain",
  "Canadian",
  "Kingfisher",
  "Washita",
  "Garvin",
  "Travis",
  "Love",
  "Tillman",
  "Cotton",
  "Harmon",
  "Greer",
  "Beckham",
  "Roger Mills",
  "Alfalfa",
  "Woods",
  "Major",
  "Woodward",
  "Cimarron",
  "Tulsa",
  "Creek",
  "Wagoner",
  "Rogers",
  "Payne",
  "Nowata",
  "Mayes",
  "Muskogee",
  "Okmulgee",
  "Pittsburg",
  "Sequoyah",
  "Pushmataha",
  "Atoka",
  "Coal",
  "Latimer",
  "Le Flore",
  "Kay",
  "Mccurtain",
  "Okfuskee",
  "Collin",
  "Denton",
  "Rockwall",
  "Navarro",
  "Van Zandt",
  "Kaufman",
  "Hunt",
  "Rains",
  "Camp",
  "Titus",
  "Bowie",
  "Gregg",
  "Nacogdoches",
  "Trinity",
  "Freestone",
  "Angelina",
  "San Augustine",
  "Tarrant",
  "Parker",
  "Hood",
  "Somervell",
  "Palo Pinto",
  "Montague",
  "Cooke",
  "Archer",
  "Wilbarger",
  "Young",
  "Baylor",
  "Erath",
  "Jack",
  "Shackelford",
  "Eastland",
  "Callahan",
  "Throckmorton",
  "Milam",
  "Coryell",
  "Mclennan",
  "Lampasas",
  "Falls",
  "Bosque",
  "Runnels",
  "Mcculloch",
  "Coleman",
  "Llano",
  "San Saba",
  "Concho",
  "Kimble",
  "Tom Green",
  "Irion",
  "Reagan",
  "Coke",
  "Schleicher",
  "Sutton",
  "Sterling",
  "San Jacinto",
  "Grimes",
  "Matagorda",
  "Fort Bend",
  "Colorado",
  "Austin",
  "Wharton",
  "Brazoria",
  "Waller",
  "Galveston",
  "Brazos",
  "Burleson",
  "Victoria",
  "Refugio",
  "De Witt",
  "Goliad",
  "Lavaca",
  "Bexar",
  "Bandera",
  "Frio",
  "Mcmullen",
  "Atascosa",
  "Kerr",
  "Live Oak",
  "Webb",
  "Zapata",
  "Comal",
  "Bee",
  "Guadalupe",
  "Karnes",
  "Gonzales",
  "Nueces",
  "Jim Wells",
  "San Patricio",
  "Kenedy",
  "Aransas",
  "Jim Hogg",
  "Kleberg",
  "Hidalgo",
  "Starr",
  "Willacy",
  "Bastrop",
  "Burnet",
  "Blanco",
  "Hays",
  "Gillespie",
  "Uvalde",
  "Dimmit",
  "Zavala",
  "Kinney",
  "Real",
  "Val Verde",
  "Maverick",
  "Lipscomb",
  "Parmer",
  "Hemphill",
  "Randall",
  "Hartley",
  "Dallam",
  "Deaf Smith",
  "Castro",
  "Lamb",
  "Ochiltree",
  "Carson",
  "Hansford",
  "Swisher",
  "Collingsworth",
  "Childress",
  "Dickens",
  "Cottle",
  "Donley",
  "Foard",
  "King",
  "Motley",
  "Briscoe",
  "Hockley",
  "Cochran",
  "Terry",
  "Bailey",
  "Crosby",
  "Yoakum",
  "Lubbock",
  "Garza",
  "Gaines",
  "Lynn",
  "Stonewall",
  "Nolan",
  "Scurry",
  "Fisher",
  "Andrews",
  "Reeves",
  "Pecos",
  "Crane",
  "Borden",
  "Glasscock",
  "Ector",
  "Winkler",
  "Upton",
  "Loving",
  "El Paso",
  "Brewster",
  "Hudspeth",
  "Presidio",
  "Culberson",
  "Arapahoe",
  "Boulder",
  "Denver",
  "Gilpin",
  "Eagle",
  "Routt",
  "Clear Creek",
  "Grand",
  "Weld",
  "Larimer",
  "Yuma",
  "Kit Carson",
  "Teller",
  "Pueblo",
  "Las Animas",
  "Baca",
  "Otero",
  "Crowley",
  "Bent",
  "Huerfano",
  "Prowers",
  "Alamosa",
  "Conejos",
  "Archuleta",
  "La Plata",
  "Costilla",
  "Saguache",
  "Chaffee",
  "Gunnison",
  "Montrose",
  "Hinsdale",
  "Dolores",
  "Montezuma",
  "San Miguel",
  "Ouray",
  "Mesa",
  "Moffat",
  "Pitkin",
  "Rio Blanco",
  "Laramie",
  "Goshen",
  "Niobrara",
  "Converse",
  "Sweetwater",
  "Washakie",
  "Hot Springs",
  "Natrona",
  "Weston",
  "Crook",
  "Sublette",
  "Uinta",
  "Bannock",
  "Bingham",
  "Power",
  "Caribou",
  "Bear Lake",
  "Lemhi",
  "Twin Falls",
  "Cassia",
  "Gooding",
  "Camas",
  "Jerome",
  "Minidoka",
  "Bonneville",
  "Nez Perce",
  "Idaho",
  "Latah",
  "Boise",
  "Owyhee",
  "Canyon",
  "Ada",
  "Gem",
  "Payette",
  "Kootenai",
  "Shoshone",
  "Bonner",
  "Boundary",
  "Benewah",
  "Duchesne",
  "Utah",
  "Salt Lake",
  "Uintah",
  "Tooele",
  "Daggett",
  "Rich",
  "Wasatch",
  "Weber",
  "Box Elder",
  "Cache",
  "Emery",
  "Sanpete",
  "Millard",
  "Juab",
  "Piute",
  "Maricopa",
  "Pinal",
  "Gila",
  "Pima",
  "Yavapai",
  "La Paz",
  "Mohave",
  "Greenlee",
  "Cochise",
  "Santa Cruz",
  "Navajo",
  "Apache",
  "Coconino",
  "Sandoval",
  "Valencia",
  "Cibola",
  "Bernalillo",
  "Torrance",
  "Santa Fe",
  "Socorro",
  "Rio Arriba",
  "Mckinley",
  "Taos",
  "Los Alamos",
  "Mora",
  "Catron",
  "Sierra",
  "Dona Ana",
  "Luna",
  "Curry",
  "Lea",
  "De Baca",
  "Quay",
  "Chaves",
  "Nye",
  "Esmeralda",
  "White Pine",
  "Lander",
  "Eureka",
  "Washoe",
  "Churchill",
  "Pershing",
  "Storey",
  "Carson City",
  "Elko",
  "Los Angeles",
  "Ventura",
  "San Bernardino",
  "Riverside",
  "San Diego",
  "Imperial",
  "Inyo",
  "Santa Barbara",
  "Tulare",
  "Kern",
  "Fresno",
  "San Luis Obispo",
  "Monterey",
  "Mono",
  "Madera",
  "Merced",
  "Mariposa",
  "San Mateo",
  "Santa Clara",
  "San Francisco",
  "Sacramento",
  "Alameda",
  "Napa",
  "Contra Costa",
  "Solano",
  "Marin",
  "Sonoma",
  "San Benito",
  "San Joaquin",
  "Calaveras",
  "Tuolumne",
  "Stanislaus",
  "Mendocino",
  "Del Norte",
  "Siskiyou",
  "Amador",
  "Placer",
  "Yolo",
  "El Dorado",
  "Alpine",
  "Sutter",
  "Yuba",
  "Colusa",
  "Glenn",
  "Plumas",
  "Shasta",
  "Modoc",
  "Lassen",
  "Tehama",
  "Honolulu",
  "Kauai",
  "Hawaii",
  "Maui",
  "American Samoa",
  "Guam",
  "Palau",
  "Federated States Of Micro",
  "Northern Mariana Islands",
  "Marshall Islands",
  "Wasco",
  "Clackamas",
  "Multnomah",
  "Hood River",
  "Yamhill",
  "Clatsop",
  "Tillamook",
  "Klamath",
  "Josephine",
  "Deschutes",
  "Harney",
  "Umatilla",
  "Gilliam",
  "Wallowa",
  "Malheur",
  "Snohomish",
  "Kitsap",
  "Whatcom",
  "Skagit",
  "Island",
  "Clallam",
  "Grays Harbor",
  "Pacific",
  "Cowlitz",
  "Klickitat",
  "Skamania",
  "Wahkiakum",
  "Chelan",
  "Okanogan",
  "Yakima",
  "Kittitas",
  "Spokane",
  "Whitman",
  "Ferry",
  "Pend Oreille",
  "Walla Walla",
  "Asotin",
  "Anchorage",
  "Aleutians West",
  "Lake And Peninsula",
  "Kodiak Island",
  "Bethel",
  "Aleutians East",
  "Wade Hampton",
  "Dillingham",
  "Kenai Peninsula",
  "Yukon Koyukuk",
  "Valdez Cordova",
  "Bristol Bay",
  "Matanuska Susitna",
  "Nome",
  "Yakutat",
  "Fairbanks North Star",
  "Denali",
  "North Slope",
  "Northwest Arctic",
  "Southeast Fairbanks",
  "Skagway Hoonah Angoon",
  "Haines",
  "Wrangell Petersburg",
  "Sitka",
  "Ketchikan Gateway",
  "Prince Wales Ketchikan"
].sort();